feat: SiteHeader has been rebuilt
sparkbox/sparkeats pull request #424
Opened 2022-10-17 19:19 UTC by catheraaine

This pull request addresses issue #401 

## What changed?
- The `SiteHeader` component has been rebuilt from the old design.
- Updated some SCSS file names for a more consistent naming convention.
- Because nested landmarks fail aXe linting, I had to chose between a `nav` and a `header` element. Either works, so I followed the issue and used a `nav` element. This is a little weird with the `h1` element so I'm open to changing that. 
- Cypress is not yet set up, so no tests we added, but I following a format that should pass tests

## How did you test the changes?
- Manually
- Location pages are not yet set up, so I did not test any other routes, but this should show up anywhere that uses App.tsx

## Screenshots
![Screen Shot 2022-10-17 at 3 13 07 PM](https://user-images.githubusercontent.com/7475148/196262647-3aa66e4c-7096-4f27-8511-942e11b409c9.png)
![Screen Shot 2022-10-17 at 3 13 00 PM](https://user-images.githubusercontent.com/7475148/196262652-4087e34c-556f-4d6c-b976-a65d9e5174bd.png)
![Screen Shot 2022-10-17 at 3 15 49 PM](https://user-images.githubusercontent.com/7475148/196263126-84ff43d6-964a-47fb-bff7-5d9c9df7c167.png)

2022-10-18 12:27 UTC, yosevu requested changes
Yeah, the nav with an h1 is weird because we usually put lists in navs, although I see they [can have other elements too](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/nav#examples). 

I'm still leaning toward the header though now that I am aware of the nested landmarks issue and also since we are calling the component header anyway so I say let's go with the header instead!

2022-10-18 12:31 UTC, yosevu commented
The link works great! You can test the link from other routes if you type them out e.g. http://127.0.0.1:5173/sparkeats/locations/1

<img width="899" alt="Screen Shot 2022-10-18 at 9 05 46 PM" src="https://user-images.githubusercontent.com/16216104/196429358-377dc59d-17b1-4f8c-9cd1-342dfb6fbe9d.png">

2022-10-18 13:32 UTC, catheraaine commented
@yosevu updated with a `header` element in place of a `nav`!

2022-10-19 10:08 UTC, yosevu approved these changes

2022-10-19 10:11 UTC, merged